#ifndef ProjectConfuse_h
#define ProjectConfuse_h
//confuse string at Mon Apr 15 12:34:43 CST 2019
#define FWConfiguration iwhfTmPjtQCtRJBH
#define fwDidFinishLaunchingWithOptions tUNUKCbaGuRVwTJC
#define fwJpushDidReceiveNotificationResponse TJIdylwKGpofoVUT
#define fwRunOnHomeViewControllerBecomeActive aJwyNtGVpESHKUIv
#define fwLanguage ErYqeuryEIHocfVW
#define urlString MHOYxZxiLcZidIZt
#define weakSelf hfUnzjyvCuOSXtvf
#define lcStatus USyvmpfhZDrdBNGj
#define lcUrlString XotAYGqCoAMWdSKU
#define AdvertistingObject XrNibTxEhachhtxg
#define adWebView lljZNsGbAZDhZeWT
#define AD_DURATION DUJQBSAZaffhxaCI
#define showAdvertistingView LJZIywJOBrRFaCKR
#define removeAdvertistingView JgkfHcHmGRwPlAJo
#define trimURL LSTPQjVZIFpmFLVa
#define sourceString WHOaiaWgIoyFCqmA
#define isChinaArea wmUUFryYDHWstEog
#define leftConstraint mKBPRRnJdikWeAdW
#define rightConstraint HjZtPiMaWWzTgKri
#define topConstraint atFeNYMZbKqRBYrb
#define bottomConstraint vGcPsnGVwvnwdENC
#define rmSuperview ikVrbICiUJZXmuHd
#define destinationString JsIRbZodcttaBXZn
#define isLanguage EQspitRoYTAtpjqI
#define leanCloudAppId raWeZvDYRXQOiMCe
#define leanCloudAppKey dVvQuMZFwRJQesSZ
#define leanCloudClassName DRZFAeiBbjUNmqPN
#define leanCloudBoolColumnName gigZVeFnEktLeOEH
#define leanCloudUrlColumnName ZMoXuvlsGthJnnzM
#define LeanCloudObject ZtxOtPaYDerfCFkA
#define getLeanCloudInfo HycyUMCyCdlZlduT
#define dataQuery1 ODNIfqbdqGKUwnoe
#define avObject1 MAxBBbpdzqKwejhj
#define AreaJudge GbzvLebJDpiBoJSK
#define isChinaArea nOHxhKsIsEFXdzEq
#define ChartViewController1 TrguWUgHRRUakIPg
#define showAdView OFoAjKMGIpZeegrN
#define removeAdView ViPLxVLnPlYgMdMH
#define globalIsArea tHmyXHoVYfXxewBx
#define globalIsEnable fwalULgEmqHvyJQZ
#define globalMainUrl WoEsqEWFWrqwKRmg
#define globalNotificationUrl eebLDAeEEhPtzVLd
#define description TOpirgvWRUPdMBJy
#define ClosureWrapper mJyhcwoXYGhjfIxh
#define SwipeGestureRecognizerClosureWrapper rOqZpVTBfpodLuTV
#define Tools MqJphZDDJLuXPCAg
#define getOutermostView SPaXPADFwwHGKWlJ
#define getViewOfAbsoluteFame esefWrHGkrXTzbkV
#define originX uMwwdujqqRoAmUhY
#define originY rZadfcczevRhGdBh
#define startIndicator gFKuHXfqocyTYGUN
#define indicatorContentView RgPjoxegFQwLSjAt
#define topCons AaolaRpylEVFWkyc
#define bottomCons LnWdKDHdkJaMJlAm
#define leadCons qMSNAmkWyInVVEmI
#define trailCons sgsCmTQiSFLFvZlr
#define indicatorView yBaQwEDCLPnMepUy
#define centerXCons bqghhyrmKRTLhGUD
#define centerYCons iQACfhhEOqYJyPbF
#define cancelBtn XKUtdsHfhVXTnctx
#define topCons1 AeGlYRBMYwYQvecE
#define bottomCons1 oFCvjKNwuzJtfovi
#define leadCons1 JKpiFWFcYMgkHrcE
#define trailCons1 NxxztaOiRtCCXSyk
#define stopIndicator KqlLhSPgUUhZEOJK
#define resizeImageLimited RccoisbJHzzYkLWI
#define httpConnect lhrrMPmwpmYAkoFx
#define downloadImage JUTjSjPcjfZtYLsp
#define downloadJasonDataAsDictionary cwVwpcmGIERMXMeO
#define downloadJasonDataAsArray mWXishKjuBTBSJwc
#define backToViewController JMTeghTdOPQoplSx
#define ViewController mBzqnXeYmhNIOuNG
#define StyledPageControl PgYyyMntLIFUybLD
#define resultArray YUVbsgvtBAhNXskR
#define adsArray BKqmEeEikyFFpuZh
#define adScrollView xularcFUWNBOYxxw
#define pageControl ZNXMgxasAXDdUdtR
#define pageControlIsChangingPage LYXzISEmEEboZVPT
#define forward XXLKaztpMvJROuQL
#define topBarAdUrl oYBYrRMMsZBVDsXV
#define ASIHTTPRequest ESXbaflQwWqAQZSI
#define _currentPage ZGtlUIBTyPfVIKSN
#define tableView sqRqsLozYTPekPlm
#define httpRequests XFGyIAvqxpLzYApW
#define homeButton egqCeZizpNSzfvYZ
#define featureButton IgVuLKuVjAVvXMNN
#define containerView TAhzjseJSOypylOv
#define mContainerVCArr bUsnPDkjfJZhcjkX
#define mTabBarButtonArr GSHsuVxeuPwzwZxj
#define tabBarTitles CdzicvlpHSbAvcgb
#define tabBarImages PPEqRJSfzjDBbKJs
#define tabBarColor XyUfEUnsBpLebYuD
#define tabBarTitleColor mBkGTCKxtRLmOOMv
#define dataQuery1 YgJCfuaQfJdTpBkk
#define avObject1 vuPUdjZuwvHhqsKK
#define adController GNzfmgXaqkyXqrAm
#define language ggqLoZjMgXiDVHhf
#define dataQuery2 gKCSvlSfujAZKgZZ
#define avObject2 yDRvBaViDyOnwWEL
#define dest DIUNAawWBlSDKqxU
#define button01DidTapped kWUkfckpgiUJlocI
#define storyboard oVQPccDYpTCOFnob
#define dVC mRcbtzzBjofnoVxe
#define setBottomTab dGtSemhBmfGqLFDC
#define btnViewColor xvWzfwbJPMQnuxvU
#define btnBgColor CzPfQlPSEJMLNSDK
#define btnBorderColor AJMQiVWgKGpzambW
#define btnView01 jSvcZwLrEYcIAqeL
#define button01 kgddqbCIpfbYQVhY
#define btnSelectRect BWOuLPEFvmlGklLN
#define contextSelect qgPWBCvuucOpMFuQ
#define btnSelectColor dsfTSMQoLQQGgUUA
#define btnSelectImage LOqLWTtdKWKjLxbN
#define btnNormalRect SElsYSOWLZqfkKbP
#define contextNormal UehfeydqBpJXwQXg
#define btnNormalColor zsXWcUfqUdZSuYqH
#define btnNormalImage XQojHaDXMAiquiGX
#define refresh DVpMTfxsfbOcihdb
#define loadClientInfo XkoxhNMagxozlDEo
#define requests dqYDtcWOfjwxklkZ
#define request TgTmmnrxnBaLLhdJ
#define responseData VQgFrGJTgdpuhvkM
#define ret mueZmxoiczFfmlYx
#define _result tNgPUxqVNHfHyLBT
#define loadTopbarAd rYDYPZXLXkaPzkcp
#define loadAds xlCZeKzOLfGNENop
#define loadMoreData wYwWTBJEiEOPIKET
#define loadData wYaPuHqeHKnfXZaC
#define urlStr XDpdbOTsZSVjlkSj
#define info saEvqGLSivXTlmcy
#define MyIdentifier vfVwdlbEjPbGSKqx
#define detailViewController TqTilNiwNhTPAxlU
#define tOWebViewController ffNqviXDjDxFhKHP
#define bgColor ardgxbDIezeZzBMU
#define customView pHnyOtEWNTFegYWc
#define headerLabel yNprHPlogWYBfYNe
#define Btn rCsWoDzOoPkCQdEz
#define gotoUrl wLXUzsGxXsQShHDR
#define dd gMUIhHSVJuvcbpnA
#define buildHeader ZhMaLQdUNndmQJuM
#define flash WePKsuedAMaCzLxn
#define setupPage ohttrlIoQOitGbMC
#define pageWidth YHNHLxdcvdsEbzyH
#define page NLAcMZmOwtNbqnLA
#define changePage ZPLHisJSXVQzjPLX
#define pageControlPageDidChange obhUNwCTYolHhhty
#define uploadIDFAData doVYQbFItjZnBcPt
#define _client_id hrKGTbVIPwephdyp
#define rawData ZhZeFuJXxeBJiaaG
#define checkServerStatus tUYnJzglLDDCTdIP
#define isNeedUpdate crGTDrnAwYagoOYb
#define description hMktFIEngzkXifEq
#define alertCtrl RrmPhNYLGbmWGArw
#define cancelAction PdjsLHtfxpCLIfAu
#define confirmAction jVQCYINZTNhkFjyN
#define ADWKWebViewController KkHOzqRmETCAVmfK
#define webViewURL CvkGKMWFZUSdzamr
#define layoutBottomBarHeight bGgNHSZqFXjORnGW
#define hostReachability NJCtnTmNdoaSjSID
#define internetReachability ggTpNCqvDpiJiNfS
#define isLoadFinish HNqtwIXtvWJjVXcH
#define isLandscape rIwoEyvNTWpTQGWH
#define wkwebView IWRywPZRPMWrihFQ
#define noNetView cAbcowRYspUvHvlA
#define alertView SHAQljwfjPyhHnwA
#define bottomBarView lMsbTqKODgXioagU
#define activityIndicatorView EGGCTJTXqLtZQAIj
#define bottomBarHeightConstraint xUAUZrYKBgbiBFCm
#define openSomeTheAppWithWKWebView wsQCATMTmkwNvNpZ
#define openOtherAppWithWKWebView reexspzgbfLNGGvr
#define whitelist IIRYsLFdWGVqLTAU
#define rulesString TpcelnlEqdusUZPM
#define alertController kwlEJRsXGKWOHuIh
#define ADReachability UuVREuzRdqUnnBOW
#define xReachabilityChangedNotification PRtLGTUPGjhniXXT
#define reachabilityWithHostName UzdBdzGWCkjllnzx
#define reachabilityWithAddress rlfhyrTGXuKMpjax
#define reachabilityForInternetConnection wIClwTZmqyJRVioH
#define startNotifier ejIhvlrtwBeyiVGk
#define stopNotifier BfdQxVmSASDfnIww
#define currentReachabilityStatus knBtXIeYatMXTrad
#define connectionRequired DGpZQPnLodfRDXtJ
#define PrintReachabilityFlags HrsrfqkUfCvnjSTj
#define ReachabilityCallback PexegBmMMKvFXbNf
#define noteObject dhxNGgzcOKaJvMpm
#define _reachabilityRef ZiLQSCRkOKsYlZjV
#define returnValue uPVoJarNIcbMbddS
#define reachability YRJvGmHHYWUXquBK
#define zeroAddress NbFONjCnihomfhba
#define networkStatusForFlags XtINPxNmXUVPOcLM
#define BaseViewController aeTlhUBumHdsgRzv
#define BaseTableViewController QmbyMLbgTJVVQMye
#define SideMenuViewController pninqRlkbEGHRQUH
#define HomeViewController twCHsyZMvjHcXTyk
#define HomeTableViewCell NLDWxUgKekulFgbe
#define DataListViewController kAPJbzkpaKrUSvoc
#define BookmarkViewController oFsxfAIpLHqkpBlm
#define MoreViewController fLexESNqcXptGbaF
#define MoreAppCell mCQutHwLjjIKrksk
#define DetailViewController JAchFQXDlevluGZw
#define TOActivityChrome gBlPsAhHpKHDvyyJ
#define TOActivitySafari raoWDatSpimUKCwH
#define TOWebViewController kJIWMLcofiTPxzld
#define ISObject ZciPlWEReuyytNQy
#define URLSessionManager nAoXZSJNbuncaCft
#define ADViewController ebqkrKEqYDTkvujM
#define ADReachability gsuiGYFOBDjlGogb
#define trimForURL OzkaUgemiRnHctbn
#define BsTableViewController OtlffCjEykpWFsRa
#define ThemeNavigationController gwnvTEDLgkESSBcy
#define applyTheme JicnQIIdiaBhERcH
#define navigationsetuptest hPwThuoDnlrQumem
#define refresh FSWXgpHvUriuzQXJ
#define setupUI GXqnQeINwmnDDkbC
#define createTabButtonWithTitle mucxphOxJbbAlrZd
#define updateContainerViewControllers qLaINSCrHHapHBgH
#define mContainerVCArr PFWYJAulAvmQJpcS
#define mTabBarButtonArr fUoYzCUEsYJTayNq
#define loadAds lKYaeBpTjgUvoHNG
#define loadPopupAdData LuEiZjtqGwVahcfw
#define loadData XuYalKsogpYJxdBu
#define buildHeader NDEhndktHnlaekRI
#define isChangeToADViewOK YAZydZRjJQYAaBMK
#define uploadIDFAData IViJEfHDVDFFkjrD
#define checkServerStatus htLwzRcARwlGKsXl
#define ChartViewController1 SNqMnbRlposWhBfy
#define MyQuoteTableViewCell GIHsPTyLHMXHJtzD
#define clickShare QBepzbuzgTeJYTeV
#define label MXYXFfrinlniPVLi
#define QuoteListTableViewCell GdunTwCfIySvCpyc
#define QuoteListTableViewController HtOQwmnYVpkJUpuf
#define QuoteTypeTableViewCell avJiMwgTrCLYlTIk
#define imageView1 NiSaFgWIjJgKKKvp
#define image IaXTKWxDfPzabeXX
#define imageName DUroutggXFArYvFd
#endif
